image: maven:3.9.4-eclipse-temurin-17

stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository

services:
  - name: postgres:15
    alias: postgres

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  POSTGRES_DB: testdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

deploy:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 157.245.67.28 >> ~/.ssh/known_hosts
  script:
    - scp target/*.jar root@157.245.67.28:/opt/manas-training-service/manas-training-service/

    - ssh root@157.245.67.28 "cd /opt/manas-training-service/manas-training-service && ./deploy.sh"
  only:
    - main
  when: manual