version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: manas-postgres-dev
    ports:
      - "8888:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      TZ: Asia/Bishkek
    volumes:
      - manas_postgres_dev_data:/var/lib/postgresql/data
      # - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  manas_postgres_dev_data:
