package manasTrainingService.entity;

public enum NotificationType {
    TEST_ASSIGNED,
    TEST_RESULT_PUBLISHED,
    TEST_CLOSED,
    NEW_SCHEDULE,
    SCHEDULE_CHANGED,
    ATTENDANCE_MISSED,
    NEW_STUDENT_ENROLLED,
    CERTIFICATE_ISSUED,
    COURSE_ENROLLMENT,
    COURSE_APPLICATION_SUBMITTED,
    COURSE_APPLICATION_APPROVED,
    COURSE_APPLICATION_REJECTED,
    COURSE_APPLICATION_COMMENT_ADDED,
    MATERIAL_ADDED,
    QUIZ_OPENED,
    MEETING_SCHEDULED,
    MEETING_RECORDING_AVAILABLE,
    GENERAL,
    COURSE_INSTANCE_FINISHED
}
